cluster.name: "es-cluster"
node.name: "node1"
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["es-node1","es-node3","es-node3"]
discovery.zen.minimum_master_nodes: 2

http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "Authorization"
path.repo: ["/var/snapshots"]